version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    networks:
      - bookstore
    environment:
      - spring.profiles.active
      - spring.datasource.url
      - spring.datasource.driver-class-name
      - spring.datasource.username
      - spring.datasource.password
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - bookstore-db:/var/lib/postgresql/data
    networks:
      - bookstore
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    expose:
      - "5432"
volumes:
  bookstore-db:
networks:
  bookstore: