version: "3.8"

services:
  backend:
    image: guap/bookstore-backend:0.0.1
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - labs
    environment:
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_DRIVERCLASSNAME
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
  db:
    image: postgres:16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - labs
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
volumes:
  db:
networks:
  labs:
