version: "3.8"

services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    networks:
      - bookstore
    environment:
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_DRIVERCLASSNAME
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - bookstore-db:/var/lib/postgresql/data
    networks:
      - bookstore
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    expose:
      - "5432"
volumes:
  bookstore-db:
networks:
  bookstore:
