spring:
    datasource:
        url: jdbc:h2:mem:bookstore
        driver-class-name: org.h2.Driver
        username: sa
        password: secret
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
