spring:
  datasource:
    url: jdbc:h2:mem:bookstore
    driver-class-name: org.h2.Driver
    username: sa
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  flyway:
    locations: classpath:/db/migration
