DROP TABLE IF EXISTS books CASCADE;

DROP TABLE IF EXISTS invoice_items CASCADE;

DROP TABLE IF EXISTS invoices CASCADE;

DROP TABLE IF EXISTS receipt_items CASCADE;

DROP TABLE IF EXISTS receipts CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE
    books (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        isbn varchar(255),
        author varchar(255),
        title varchar(255),
        price numeric(38, 2),
        PRIMARY KEY (id)
    );

CREATE TABLE
    invoice_items (
        invoice_id integer NOT NULL,
        line_number integer,
        book_id integer,
        quantity integer,
        price numeric(38, 2),
        sum numeric(38, 2)
    );

CREATE TABLE
    invoices (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        number varchar(255),
        date timestamp(6),
        sum numeric(38, 2),
        PRIMARY KEY (id)
    );

CREATE TABLE
    receipt_items (
        receipt_id integer NOT NULL,
        line_number integer,
        book_id integer,
        quantity integer
    );

CREATE TABLE
    receipts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        number varchar(255),
        date timestamp(6),
        PRIMARY KEY (id)
    );

CREATE TABLE
    users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        username varchar(255),
        password varchar(255),
        enabled boolean,
        role varchar(255) CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER')),
        PRIMARY KEY (id)
    );

ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_book_id_fkey FOREIGN KEY (book_id) REFERENCES books;

ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices;

ALTER TABLE receipt_items ADD CONSTRAINT receipt_items_book_id_fkey FOREIGN KEY (book_id) REFERENCES books;

ALTER TABLE receipt_items ADD CONSTRAINT receipt_items_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES receipts;
