name: Lint Dockerfile

on:
  # push:
  #   paths:
  #     - .github/workflows/lint_and_publish.yml
  workflow_dispatch:

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile
